FORCE_ALL=true
RUN_SONAR_BACKEND=false
RUN_SCAN_FRONTEND=false
RUN_SCAN_WORKER=false
RUN_TRIVY=true
BUILD_SRM_API=true
BUILD_SRM_DB=true
BUILD_SRM_DASHBOARD=true
BUILD_SRM_OCR_WORKER=true
BUILD_PROMTAIL=true
BUILD_NODE_EXPORTER=true
BUILD_SONAR_DB=true
BUILD_SONARQUBE=true
BUILD_GRAFANA=true
BUILD_JENKINS_SRM=true
