name: srm-oriental-gateway


services:
# ==============================================================================
# STACK PROXY : Point d'entrée unique (Optimisée pour Ansible)
# ==============================================================================
  srm-admin-proxy:
    image: nginx:${NGINX_VERSION}
    container_name: srm-admin-proxy
    ports:
      - "8888:80"
    volumes:
      - ./infra/nginx/admin.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - ops-net
      - sec-net
    restart: always
# ==============================================================================
# STACK CORE : Application Métier
# Déploiement : Base de données, API, Dashboard, Worker OCR, n8n, Mailpit
# ==============================================================================
#----------------------------------------------------------------------------
# PRIMARY DATABASE (PostgreSQL)
# ----------------------------------------------------------------------------
  srm-db:
    build:
      context: .
      dockerfile: infra/docker/db.Dockerfile
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION}
    container_name: srm-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGPORT=${DB_INTERNAL_PORT}
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -p ${DB_INTERNAL_PORT} -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5' # Limit to 50% of a single CPU core
    networks:
      - back-net
# ----------------------------------------------------------------------------
# BACKEND API (.NET)
# ----------------------------------------------------------------------------
  srm-api:
    build:
      context: ./src/backend
      dockerfile: ../../infra/docker/api.Dockerfile
      args:
        DOTNET_VERSION: ${DOTNET_VERSION}
        API_INTERNAL_PORT: ${API_INTERNAL_PORT}
        API_ENV: ${API_ENV}
    container_name: srm-api
    environment:
      - "ConnectionStrings__DefaultConnection=Host=${DB_SERVICE};Port=${DB_INTERNAL_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
    volumes:
      - ./src/workers/ocr-service/uploads:/app/uploads
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0' # Allow up to 1 full CPU core for better performance
    networks:
      - web-net
      - back-net
      - ops-net
    restart: always
# ----------------------------------------------------------------------------
# FRONTEND DASHBOARD (React + Nginx)
# ----------------------------------------------------------------------------
  srm-dashboard:
    build:
      context: .
      dockerfile: infra/docker/dashboard.Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
        NGINX_VERSION: ${NGINX_VERSION}
        DASHBOARD_INTERNAL_PORT: ${DASHBOARD_INTERNAL_PORT}
    container_name: srm-dashboard
    ports:
      - "${DASHBOARD_EXTERNAL_PORT}:${DASHBOARD_INTERNAL_PORT}"
    volumes:
      - ./infra/nginx/public.conf:/etc/nginx/conf.d/default.conf:ro
      - ./infra/nginx/security_headers.conf:/etc/nginx/conf.d/security_headers.conf:ro
    deploy:
      resources:
        limits:
          memory: 128M
    networks:
      - web-net
# ----------------------------------------------------------------------------
# WORKER OCR (Python + Tesseract)
# ----------------------------------------------------------------------------
  srm-ocr-worker:
    platform: linux/amd64
    build:
      context: .
      dockerfile: infra/docker/worker.Dockerfile
      args:
        BASE_IMAGE:    ${BASE_IMAGE}
        SRM_USER_ID:   ${SRM_USER_ID}
        SRM_GROUP_ID:  ${SRM_GROUP_ID}
        WORKER_ENV:    ${WORKER_ENV}
    container_name: srm-ocr-worker
    volumes:
      - ./src/workers/ocr-service/uploads:/home/srm_worker/app/uploads      
      # 2. LE NOUVEAU : Le volume pour le code en live (Live Reloading)
      #- ./src/workers/ocr-service/tests:/home/srm_worker/app/tests
      #- ./src/workers/ocr-service/main.py:/home/srm_worker/app/main.py
    deploy:
      resources:
        limits:
          memory: 1G                                    # OCR is CPU/Memory intensive
    networks:
      - back-net
      - ops-net
    restart: on-failure
# ----------------------------------------------------------------------------
# Notification System (n8n)
# ----------------------------------------------------------------------------
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    platform: linux/amd64
    user: "1000:1000"
    ports:
      - "${N8N_EXTERNAL_PORT}:${N8N_INTERNAL_PORT}"
    environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=${N8N_INTERNAL_PORT}
      - N8N_PROTOCOL=http
      - NODE_ENV=development
      - WEBHOOK_URL=http://localhost:${N8N_EXTERNAL_PORT}/ 
      - N8N_EXECUTORS_PROCESS=main
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - back-net
      - ops-net
    restart: unless-stopped
# ----------------------------------------------------------------------------
# Emails Mock (Mailpit)
# ----------------------------------------------------------------------------
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    platform: linux/amd64
    restart: always
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP
    networks:
      - back-net
# ==============================================================================
# STACK DEVOPS : CI/CD et Qualité de code 
# ==============================================================================

# ----------------------------------------------------------------------------
# CI/CD PIPELINE (Jenkins)
# ----------------------------------------------------------------------------
  jenkins-srm:
    build:
      context: .
      dockerfile: infra/docker/jenkins.Dockerfile
    container_name: jenkins-srm
    user: root # Required to interact with host Docker socket
    volumes:
      - jenkins-srm_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:ro # Docker-in-Docker capability
    environment:
      - JAVA_OPTS=-Xmx512m -Xms512m
      # - JENKINS_OPTS=--prefix=/jenkins --httpPort=${JENKINS_INTERNAL_PORT}
    ports: 
      - "${JENKINS_EXTERNAL_PORT}:${JENKINS_INTERNAL_PORT}"
    deploy:
      resources:
        limits:
          memory: 1.5G 
    networks:
      - sec-net
      - ops-net
    restart: unless-stopped
# ----------------------------------------------------------------------------
# CODE QUALITY & SECURITY (SonarQube)
# ----------------------------------------------------------------------------
  # ------ SonarQube Database (PostgreSQL) ------
  sonar-db:
    build: 
      context: .
      dockerfile: infra/docker/sonar-db.Dockerfile
      args:
        SONAR_DB_VERSION: ${SONAR_DB_VERSION}
        SONAR_DB_NAME: ${SONAR_DB_NAME}
        SONAR_DB_USER: ${SONAR_DB_USER}
        SONAR_DB_PASSWORD: ${SONAR_DB_PASSWORD}
        SONAR_DB_INTERNAL_PORT: ${SONAR_DB_INTERNAL_PORT}
    container_name: sonar-db
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - sec-net
    volumes:
      - sonar_db_data:/var/lib/postgresql/data
  # ----- SonarQube Server ------
  sonarqube:
    build:
      context: .
      dockerfile: infra/docker/sonarqube.Dockerfile
      args:
        SONAR_VERSION: ${SONAR_VERSION}
        SONAR_INTERNAL_PORT: ${SONAR_INTERNAL_PORT}
        SONAR_JDBC_USERNAME: ${SONAR_JDBC_USERNAME}
        SONAR_JDBC_PASSWORD: ${SONAR_JDBC_PASSWORD}
        SONAR_DB_NAME: ${SONAR_DB_NAME}
        SONAR_JDBC_URL: ${SONAR_JDBC_URL}
    container_name: sonarqube
    ports:
      - "${SONAR_EXTERNAL_PORT}:${SONAR_INTERNAL_PORT}"
    environment:
      - SONAR_WEB_PORT=${SONAR_INTERNAL_PORT}
      - SONAR_WEB_JAVA_OPTS=-Xmx1G -Xms1G 
      - SONAR_CE_JAVA_OPTS=-Xmx1G -Xms1G
      - SONAR_SEARCH_JAVA_OPTS=-Xmx512m -Xms512m
      #  - SONAR_WEB_CONTEXT=/sonar
    deploy:
      resources:
        limits:
          memory: 2G
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - sec-net
    depends_on:
      - sonar-db
# ==============================================================================
# STACK MONITORING : Observabilité PLG 
# ==============================================================================

# ==============================================================================
# Prometheus 
# ==============================================================================
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    platform: linux/amd64
    user: root
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.external-url=http://localhost:8888/prometheus/'
      - '--web.route-prefix=/prometheus'
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - ops-net
    restart: unless-stopped
# ==============================================================================
# Loki 
# ==============================================================================
  loki:
    image: grafana/loki:latest
    container_name: loki
    platform: linux/amd64
    user: "0"
    volumes:
      - ./infra/loki/loki-config.yml:/etc/loki/local-config.yaml:ro
      - loki_data:/tmp/loki
    command: -config.file=/etc/loki/local-config.yaml
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - ops-net
    restart: unless-stopped
# ==============================================================================
# Grafana
# ==============================================================================
  grafana:
    build:
      context: .
      dockerfile: infra/docker/grafana.Dockerfile
      args:
        GRAFANA_VERSION: ${GRAFANA_VERSION}
        GRAFANA_INTERNAL_PORT: ${GRAFANA_INTERNAL_PORT}
        # On passe le mot de passe en ARG seulement si on veut le baker, 
        # mais c'est mieux en ENV de runtime ci-dessous.
    container_name: grafana
    # --- TOUTE LA CONFIGURATION EST ICI ---
    environment:
      # Sécurité
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      # Réseau & Proxy (C'est ici que tu règles ton problème de 502)
      - GF_SERVER_HTTP_PORT=${GRAFANA_INTERNAL_PORT}
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:8888/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      # Divers
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infra/grafana/provisioning:/etc/grafana/provisioning:ro
    networks:
      - ops-net
    deploy:
      resources:
        limits:
          memory: 512M
    restart: unless-stopped
# ==============================================================================
# Promtail 
# ==============================================================================
  promtail:
    build:
      context: .
      dockerfile: infra/docker/promtail.Dockerfile
      args:
        PROMTAIL_VERSION: ${PROMTAIL_VERSION}
        PROMTAIL_INTERNAL_PORT: ${PROMTAIL_INTERNAL_PORT}
    container_name: promtail
    # CRUCIAL : root est nécessaire pour lire /var/run/docker.sock
    user: root 
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.2'
    networks:
      - ops-net
    volumes:
      # 1. Ta configuration (celle qui contient docker_sd_configs)
      - ./infra/promtail/promtail-config.yml:/etc/promtail/config.yml:ro
      # 2. Le socket Docker en lecture seule (:ro) pour la découverte auto
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log:/var/log:ro
    restart: unless-stopped
# ==============================================================================
# Node Exporter 
# ==============================================================================
  node-exporter:
    build:
      context: .
      dockerfile: infra/docker/node-exporter.Dockerfile
      args:
        NODE_EXPORTER_VERSION: ${NODE_EXPORTER_VERSION}
        NODE_EXPORTER_INTERNAL_PORT: ${NODE_EXPORTER_INTERNAL_PORT}
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'
      - '--web.listen-address=:${NODE_EXPORTER_INTERNAL_PORT}'
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.1'
    restart: unless-stopped
    volumes:
      - '/:/host:ro'
    networks:
      - ops-net
# ==============================================================================
# CAdvisor 
# ==============================================================================
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    # 🛡️ SYNTAXE OFFICIELLE (Basée sur ton aide -v)
    command:
      - '-port=8081'
      - '-docker_only=true'
      - '-store_container_labels=true'
      - '-whitelisted_container_labels=container_group,project,component'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.2'
    networks:
      - ops-net
    restart: unless-stopped
# ==============================================================================
# NETWORKS
# ==============================================================================
networks:
  ops-net:
  sec-net:
  web-net:
  back-net:
# ==============================================================================
# VOLUMES
# ==============================================================================
volumes:
  postgres_data:
  n8n_data:
  jenkins-srm_data:
  sonar_db_data:
  sonarqube_data:
  sonarqube_extensions:
  prometheus_data:
  loki_data:
  grafana_data:
