server {
    listen 80;
    server_name localhost;

    # Docker internal DNS
    resolver 127.0.0.11 valid=30s;
    
    # --- 2. Grafana (Monitoring) ---
    # Ton image montre SERVE_FROM_SUB_PATH=true et ROOT_URL avec port 8888
    location /grafana/ {
        set $target_grafana grafana:3001;
        proxy_pass http://$target_grafana;

        # 🛡️ FIX : Indispensable pour que Grafana ne se perde pas
        proxy_set_header Host $host:8888;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /grafana {
        return 301 http://$host:8888/grafana/;
    }

    # --- 3. Prometheus ---
    # Requis : --web.route-prefix=/prometheus --web.external-url=http://localhost:8888/prometheus
    location /prometheus {
        set $upstream_prometheus prometheus;
        proxy_pass http://$upstream_prometheus:9090;
        
        proxy_set_header Host $host:8888;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # --- 4. Jenkins (Working) ---
    ; location /jenkins {
    ;     set $upstream_jenkins jenkins-srm;
    ;     proxy_pass http://$upstream_jenkins:8085;

    ;     proxy_set_header Host $host:8888; 
    ;     proxy_set_header X-Real-IP $remote_addr;
    ;     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    ;     proxy_set_header X-Forwarded-Proto $scheme;
        
    ;     proxy_redirect http://$upstream_jenkins:8085/jenkins/ /jenkins/;
    ;     proxy_set_header X-Forwarded-Host $host:8888;
    ; }

    # --- 5. SonarQube ---
    # Requis : SONAR_WEB_CONTEXT=/sonar
    location /sonar {
        set $upstream_sonarqube sonarqube;
        proxy_pass http://$upstream_sonarqube:9002;

        proxy_set_header Host $host:8888;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # SonarQube est sensible aux redirects lors du login
        proxy_redirect http://$upstream_sonarqube:9002/sonar/ /sonar/;
    }

    # --- 6. Loki ---
    location /loki {
        set $upstream_loki loki;
        proxy_pass http://$upstream_loki:3101;
        proxy_set_header Host $host:8888;
    }
}