server {
    listen 80;
    server_name localhost;

    include /etc/nginx/conf.d/security_headers.conf;

    location /jenkins/ {
        proxy_pass http://jenkins-srm:8080/jenkins/;
        proxy_set_header Host $host;
    }

    location /grafana/ {
        proxy_pass http://grafana:3001/;
        proxy_set_header Host $host;
    }

    location /prometheus/ {
        proxy_pass http://prometheus:9090;
        proxy_set_header Host $host;
    }

    location /loki/ {
        proxy_pass http://loki:3101/;
        proxy_set_header Host $host;
    }

    location /n8n/ {
        proxy_pass http://n8n:5678/;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Host $host;
    }

    location /sonar/ {
        proxy_pass http://sonarqube:9002/;
        proxy_set_header Host $host;
    }
   
}