server {
    listen 8080;
    server_name localhost;

    include /etc/nginx/conf.d/security_headers.conf;

    client_max_body_size 50M;

    # --- 1. Static Files ---
    location / {
        root /usr/share/nginx/html;
        index index.html;

        try_files $uri $uri/ /index.html;
    }

    # --- 2. API Proxy ---
    location /api/ {
        proxy_pass http://srm-api:8080;

        proxy_http_version 1.1;
        proxy_set_header Connection keep-alive;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_read_timeout 300s;
        proxy_connect_timeout 300s;
    }

    location /openapi/ {
        proxy_pass http://srm-api:8080;
        proxy_set_header Host $host;
    }
    error_log /var/log/nginx/srm_public_error.log warn;
    access_log /var/log/nginx/srm_public_access.log;

}