server{
    # LISTEN_PORT is a placoholder replaced during Docker build
    listen ${DASHBOARD_INTERNAL_PORT};
    server_name localhost;

    location /{
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Essential for React Router (SPA)
        try_files $uri $uri/ /index.html;
    }
    # Performance: Gzip compression for faster loading
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Basic security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block";
}