global:
  scrape_interval: 15s 
  evaluation_interval: 15s 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          container: 'prometheus'

  - job_name: 'srm-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['srm-api:9000']
        # --- ADDED LABELS ---
        labels:
          container: 'srm-api'
          project: 'srm-oriental-gateway'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        # --- ADDED LABELS ---
        labels:
          container: 'node-exporter'