---
# =====================================================================================
#  SRM Proxy / Dashboard Configuration
# =====================================================================================

# --- Infrastructure --- 
registry_url: "my registry"
git_sha: "latest"
public_network_name: "srm_public_network"

# --- Service Naming & Ports ---
dashboard_service_name: "srm-dashboard"
dashboard_external_port: 80
dashboard_internal_port: 8080

# --- Upstream API Configuration ---
api_service_name: "srm-api"
api_internal_port: 9000
domain_name: "localhost"

# --- Resource Limits ---
dashboard_memory_limit: "128m"
dashboard_cpu_limit: "0.5"

# --- Nginx Specifics ---
nginx_client_max_body_size: "50m"
nginx_proxy_read_timeout: "300s"
nginx_proxy_connect_timeout: "300s"
docker_dns_resolver: "127.0.0.11 "
docker_dns_valid_time: 30